# Variables
EXE=GB-emulator

# Usual compilation flags
CFLAGS=-std=c11 -Wall -Wextra -g -O2 -pg
CPPFLAGS=-I../include -DDEBUG
# CPPFLAGS=-I../include
LDFLAGS=-lm -lSDL2

# Special rules and targets
.PHONY: all clean help

# Rules and targets
all: $(EXE)

$(EXE): main.o memory.o cpu.o ppu.o cartridge.o timer.o
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

main.o : main.c ../include/memory.h ../include/common.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

memory.o : memory.c ../include/memory.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

cpu.o : cpu.c ../include/cpu.h ../include/memory.h ../include/common.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

ppu.o : ppu.c ../include/ppu.h ../include/memory.h ../include/common.h ../include/cpu.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

cartridge.o : cartridge.c ../include/cartridge.h ../include/memory.h ../include/common.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

timer.o : timer.c ../include/timer.h ../include/memory.h ../include/common.h ../include/cpu.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<

clean:
	@rm -f *~ *.o $(EXE)

help:
	@echo "Usage:"
	@echo "  make [all]\t\tBuild the software"
	@echo "  make clean\t\tRemove all files generated by make"
	@echo "  make help\t\tDisplay this help"